### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by bpskishore** [confluentinc/common#174]
[ERROR] Failed to execute goal on project common-metrics: Could not resolve dependencies for project io.confluent:common-metrics:jar:5.2.0-SNAPSHOT: The following artifacts could not be resolved: io.confluent:common-utils:jar:5.2.0-SNAPSHOT, io.confluent:assembly-plugin-boilerplate:zip:resources:5.2.0-SNAPSHOT: Failure to find io.confluent:common-utils:jar:5.2.0-SNAPSHOT in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by cricket007** [comment]
Duplicates #170

**Comment by RoyalFeng** [comment]
@cricket007  Do you solve this problem?

**Comment by ouertani** [comment]
> @cricket007 Do you solve this problem?

yes

**Comment by ewencp** [comment]
Agreed this is a dupe of #170. See that issue for explanation of how to build, including dependencies.
