### ISSUE TITLE
Build fail with "Failed to execute goal on project common-logging"

### ISSUE THREAD

**Issue by samko635** [confluentinc/common#204]
My kafka project is on 'trunk' and common on 'master'.
I've successfully built kafka but on common, I get the below error. 

[INFO] assembly-plugin-boilerplate ........................ SUCCESS [  0.610 s]
[INFO] Build Tools ........................................ SUCCESS [  0.694 s]
[INFO] common ............................................. SUCCESS [  1.333 s]
[INFO] utils .............................................. SUCCESS [  0.832 s]
[INFO] metrics ............................................ SUCCESS [  1.995 s]
[INFO] config ............................................. SUCCESS [  1.546 s]
[INFO] common-logging ..................................... FAILURE [  5.408 s]
[INFO] confluent-log4j-extensions ......................... SKIPPED
[INFO] confluent-log4j2-extensions ........................ SKIPPED
[INFO] package ............................................ SKIPPED
[INFO] Common ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.692 s
[INFO] Finished at: 2019-06-04T15:36:45+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project common-logging: Could not resolve dependencies for project io.confluent:common-logging:jar:5.4.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:connect-api:jar:5.4.0-ccs-SNAPSHOT, org.apache.kafka:connect-json:jar:5.4.0-ccs-SNAPSHOT: Could not find artifact org.apache.kafka:connect-api:jar:5.4.0-ccs-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common-logging

I've cleared out my local maven repository and retried but still getting the same error. Changed the branch to different ones but it doesn't seem to be working..
Been googling for 3 hours and got nowhere.

Can anyone point me to the right direction?

**Comment by landon9720** [comment]
Hi @samko635, and progress solving this issue?

**Comment by samko635** [comment]
> Hi @samko635, and progress solving this issue?

No, I haven't heard back from anyone yet. It seems like there's no common-logging jar in maven artifactory.

**Comment by ankitchiplunkar** [comment]
I was able to build, I had to change the kafka-version to 2.4.0 in the pom file

**Comment by abhisheksahani** [comment]
any update on this i am also facing same issue

**Comment by abhisheksahani** [comment]
you'd have to build the matching Kafka branch, which you can find here (note: this is Confluent's forked repo, not apache/kafka, which likely doesn't have a 5.4.0-ccs version) [https://github.com/confluentinc/kafka](url)

**Comment by ewencp** [comment]
Yes, that's correct. The version of Kafka the pom now points at is from confluentinc/kafka, so you'd want to build from there.
