### ISSUE TITLE
mvn -pl :common-utils package fails

### ISSUE THREAD

**Issue by eamocanu** [confluentinc/common#37]
mvn -pl :common-utils package
[INFO] Scanning for projects...
[ERROR] Could not find the selected project in the reactor: :common-utils -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by ewencp** [comment]
@eamocanu This seems to be working fine for me. Can you run with the flags Maven suggests to get some more information about the error.

**Comment by eamocanu** [comment]
I've now successfully built this. I think I was running mvn install instead of the command you had on the readme file. Anyway I got an error compiling schema-registry so I'll open an issue in that repo.
Thanks
