### ISSUE TITLE
No means of removing password from logs

### ISSUE THREAD

**Issue by dehrman** [confluentinc/common#38]
AbstractConfig's constructor calls a private method that logs all key-value pairs in the config map. In the case of the JdbcSourceConnector, this includes the connection URL and password.

Unfortunately, that means that the password is then persisted in plain text for anyone with access to the logs to read.

Can we provide a means of either overriding this logging behavior or providing the password as a separate config?

**Comment by shikhar** [comment]
@dehrman closing as I think we should fix this in the JDBC source connector ^

**Comment by dehrman** [comment]
Yes! Thank you for moving it to the right place.

**Comment by cricket007** [comment]
Ping. Moved ticket has been closed
