### ISSUE TITLE
Unable to resolve the assembly-plugin-boilerplate 6.0.3 jar file 

### ISSUE THREAD

**Issue by cuichenli** [confluentinc/common#404]
```
   > Could not determine artifacts for io.confluent:assembly-plugin-boilerplate:6.0.3
      > Could not get resource 'https://packages.confluent.io/maven/io/confluent/assembly-plugin-boilerplate/6.0.3/assembly-plugin-boilerplate-6.0.3.jar'.
         > Could not HEAD 'https://packages.confluent.io/maven/io/confluent/assembly-plugin-boilerplate/6.0.3/assembly-plugin-boilerplate-6.0.3.jar'. Received status code 403 from server: Forbidden
```
The above is the error message we got when building. Checked https://packages.confluent.io/maven/io/confluent/assembly-plugin-boilerplate/6.0.3/ and looks like there is no such jar file. Can you guide what should we do to resolve the issue? Thanks!

**Comment by andrewegel** [comment]
https://github.com/confluentinc/common/blob/6.0.3-post/assembly-plugin-boilerplate/pom.xml#L9

The artifact has always been a pom, never a jar (Git blame & past releases show that). So you need to take a dependency on the pom, not a jar. I'm not entirely sure how to do that with gradle though.

**Comment by andrewegel** [comment]
Try this again, you should be getting a 404 not found instead of a 403 Forbidden now.
