### ISSUE TITLE
java.lang.IllegalArgumentException: A metric named 'MetricName' already exists, can't register another one.

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/common#86]
Hi, 
After playing with Kafka Connect I'm getting following Exception.
After connect restarting everything is OK. I don't know how to reproduce this in controlled manner.
```
java.lang.IllegalArgumentException: A metric named 'MetricName [name=offset-commit-max-time-ms, group=connector-task-metrics, description=The maximum time in milliseconds taken by this task to commit offsets., tags={connector=test_source_test_bulk, task=0}]' already exists, can't register another one.
	at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:532)
	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:256)
	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:241)
	at org.apache.kafka.connect.runtime.WorkerTask$TaskMetricsGroup.<init>(WorkerTask.java:328)
	at org.apache.kafka.connect.runtime.WorkerTask.<init>(WorkerTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.<init>(WorkerSourceTask.java:100)
	at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:445)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:404)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:852)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:108)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:866)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:862)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mtranter** [comment]
Anything on this? I'm also seeing this.

**Comment by ewencp** [comment]
This isn't actually from this repo, there are equivalent classes in Kafka that Kafka Connect uses. The relevant bug over there is https://issues.apache.org/jira/browse/KAFKA-6252. Even there, it's not an issue with the metrics classes themselves, but rather users of the classes that may not properly clean up a metric with that name before trying to reinstantiate it. It's worth pointing out that even in that case, it is a bug in a *plugin* for the framework. It's likely possible to work around the bug and still remove metrics, but one of the drawbacks of a plugin-based system is that the framework inherits some of the bugs of incorrectly implemented plugins.

I'm going to close this as it is not relevant to this repo, but feel free to follow up on the linked Kafka JIRA.

**Comment by maver1ck** [comment]
I think it difficult to say from which repo it is.
Quote: "This also happens when a connector does not properly implement stop()"

**Comment by ewencp** [comment]
@maver1ck You can tell based on the classnames in the stacktrace. Everything in this repo is under the package `io.confluent.`. Everything you reported is under `org.apache.kafka`. Is there something relevant to the `io.confluent` packages that this repo defines that are affected by your issue?

The bug you're seeing could still potentially be an issue indirectly under another repository, but afaict, it isn't an issue in this repo (i.e. it is a bug in connect, a particular connector, etc, but not confluentinc/common). As I pointed to earlier there is https://issues.apache.org/jira/browse/KAFKA-6252 to address what I can tell is the issue. It seems like it is a combined issue with the Kafka Connect framework, its metrics, and cases where its plugins fail to shut down properly (followed by subsequent re-start an re-initialization).

We're happy to help debug the issue you're having, I'm just trying to direct it to the location that will be most effective and, most importantly, get the most attention.

**Comment by maver1ck** [comment]
Understood.
So the only connection with confluent is that metric from above is created from io.confluent.connect.jdbc.JdbcSourceConnector (name: test_source_test_bulk) with following configuration
```
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "incrementing.column.name": "id",
  "transforms.createKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
  "validate.non.null": "false",
  "tasks.max": "1",
  "transforms": "createKey,extractInt",
  "transforms.extractInt.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
  "timestamp.delay.interval.ms": "0",
  "table.whitelist": "test_bulk",
  "mode": "bulk",
  "value.converter.schema.registry.url": "http://localhost:8081",
  "topic.prefix": "test_source_",
  "transforms.extractInt.field": "id",
  "transforms.createKey.fields": "id",
  "poll.interval.ms": "3600000",
  "name": "test_source_test_bulk",
  "connection.url": "jdbc:mysql://localhost:3306/test?user=root&password=x",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "key.converter.schema.registry.url": "http://localhost:8081"
}
```

**Comment by ewencp** [comment]
correct, though based on the Kafka JIRA, it sounds like something in the JDBC source may not always be shutting down correctly.

**Comment by maver1ck** [comment]
And I have problem only with bulk source mode.

**Comment by moha5282** [comment]
I am facing the same issue:-
# ./confluent_isq status jdbc_sink_oracle_foobar_01
{"name":"jdbc_sink_oracle_foobar_01","connector":{"state":"RUNNING","worker_id":"10.87.40.165:8083"},"tasks":[{"state":"FAILED","trace":"java.lang.IllegalArgumentException: A metric named 'MetricName [name=offset-commit-max-time-ms, group=connector-task-metrics, description=The maximum time in milliseconds taken by this task to commit offsets., tags={connector=jdbc_sink_oracle_foobar_01, task=0}]' already exists, can't register another one.\n\tat org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:532)\n\tat org.apache.kafka.common.metrics.Sensor.add(Sensor.java:256)\n\tat org.apache.kafka.common.metrics.Sensor.add(Sensor.java:241)\n\tat org.apache.kafka.connect.runtime.WorkerTask$TaskMetricsGroup.<init>(WorkerTask.java:328)\n\tat org.apache.kafka.connect.runtime.WorkerTask.<init>(WorkerTask.java:69)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.<init>(WorkerSinkTask.java:98)\n\tat org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:449)\n\tat org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:404)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:852)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:108)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:866)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:862)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","id":0,"worker_id":"10.87.40.165:8083"}],"type":"sink"}
root@apsrd00439:/app01/confluent-4.0.0/bin


Is there any work around for this? I am loading data from Kafka to Oracle using config file

**Comment by ewencp** [comment]
As mentioned earlier in this thread, this is not an issue in this repository. It is an issue in Kafka, https://issues.apache.org/jira/browse/KAFKA-6252, and that issue has since been resolved. The fix will be released in Kafka 1.0.1 and 1.1.0 and Confluent Platform 4.0.1 and 4.1.0.

**Comment by PercyARS** [comment]
What's the ETA for the Confluent fix?

**Comment by schliffen** [comment]
I get the same error with running bazel for compiling, that was related to permission, after I used "sudo" error disappeared!

**Comment by pirlck** [comment]
how

**Comment by pirlck** [comment]
But how can I avoid this problem without update Kafka version ?
